export enum Routes {
  home = "/",
  ErrorPage = "/error-page",
  Login = "/login",
  SignUp = "/sign-up",
  ProductGrid = "product-grid",
  About = "about",
  Cart = "cart",
  ProductPage = "product-page",
  ContactUs = "contact-us",
  PrivacyPolicy = "privacy-policy",
  HelpCenter = "help-center",
  ReturnPolicy = "return-policy",
  TrackOrder = "track-order",
  Wishlist = "wishlist",
  Checkout = "/checkout",
  Category = "/category/:categoryName",
  SubCategory = "/category/:categoryName/:subCategoryName",
  Collection = "collection",
}
