export enum Routes {
  home = "/",
  ErrorPage = "/error-page",
  Login = "/login",
  SignUp = "/sign-up",
  About = "about",
  Cart = "cart",
  ProductPage = "/products/:label",
  ContactUs = "contact-us",
  PrivacyPolicy = "privacy-policy",
  HelpCenter = "help-center",
  ReturnPolicy = "return-policy",
  TrackOrder = "track-order",
  Wishlist = "wishlist",
  Checkout = "/checkout",
  Category = "/category/:category",
  SubCategory = "/category/:category/:subCategory",
  SearchPage = "/search",
  Collection = "/collection/:collection",
  Collections = "/collection",
  PaymentConfirmation = "/confirmation",
  Blogs = "/blogs",
}
