export enum Routes {
  home = "/",
  ErrorPage = "/error-page",
  Login = "/login",
  SignUp = "/sign-up",
  ProductList = "products-items",
  About = "about",
  Cart = "cart",
  ProductPage = "/products/:label",
  ContactUs = "contact-us",
  PrivacyPolicy = "privacy-policy",
  HelpCenter = "help-center",
  ReturnPolicy = "return-policy",
  TrackOrder = "track-order",
  Wishlist = "wishlist",
  Checkout = "/checkout",
  // Category = "/category/:categoryName",
  SubCategory = "/category/:categoryName/:subCategoryName",
  Collection = "/collection",
  Collections = "/collections",
  CheckoutBilling = "/checkout-billing",
}
